name: NextJS CI

on:
  pull_request:
    branches: ['main', 'develop']

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - run: |
          npm ci
          npm run lint
          npm test
          npm run build
