name: NextJS CI/CD

on:
  pull_request:
    branches: ['main', 'dev']

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container: node:20

    steps:
      - run: node --version
      - run: npm --version
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run linting
        run: npm run lint

      - name: Run tests
        run: npm run test
